const ExcelJS = require('exceljs')
const { sanitizeCell } = require('./sanitizer')

const STYLES = {
  header: {
    font: { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 },
    fill: {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF1F4E79' }
    },
    alignment: { horizontal: 'center', vertical: 'middle', wrapText: true },
    border: {
      top: { style: 'thin', color: { argb: 'FF000000' } },
      bottom: { style: 'thin', color: { argb: 'FF000000' } },
      left: { style: 'thin', color: { argb: 'FF000000' } },
      right: { style: 'thin', color: { argb: 'FF000000' } }
    }
  },
  summary: {
    font: { bold: true, size: 10, color: { argb: 'FF1F4E79' } },
    fill: {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFDCE6F1' }
    },
    alignment: { horizontal: 'left' }
  },
  rowEven: {
    fill: {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFF2F2F2' }
    }
  },
  rowOdd: {
    fill: {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FFFFFFFF' }
    }
  }
}

const createWorkbook = (title, exportedBy, dateRange = {}) => {
  const workbook = new ExcelJS.Workbook()
  workbook.creator = 'Backup System'
  workbook.lastModifiedBy = exportedBy
  workbook.created = new Date()
  workbook.modified = new Date()
  workbook.properties.date1904 = false
  workbook.title = title
  workbook.subject = `Export: ${dateRange.from || ''} to ${dateRange.to || ''}`
  workbook.description = `Generated by ${exportedBy} on ${new Date().toISOString()}`
  return workbook
}

const addSummarySheet = (workbook, summaryData = {}) => {
  const worksheet = workbook.addWorksheet('Summary', {
    properties: { tabColor: { argb: 'FF1F4E79' } }
  })

  worksheet.columns = [
    { header: '', key: 'label', width: 35 },
    { header: '', key: 'value', width: 30 }
  ]

  const counts = summaryData.counts || {}
  const rows = [
    ['EXPORT SUMMARY', ''],
    ['Generated At', new Date().toLocaleString('en-IN')],
    ['Exported By', summaryData.exportedBy || ''],
    ['Date Range From', summaryData.fromDate || ''],
    ['Date Range To', summaryData.toDate || ''],
    ['', ''],
    ['RECORD COUNTS', ''],
    ['Candidate Management - Total Records', counts.candidateManagement || 0],
    ['Business Advisor - Total Records', counts.businessAdvisor || 0],
    ['CRM Telecalling - Total Records', counts.crm || 0],
    ['', ''],
    ['TOTAL RECORDS EXPORTED', counts.total || 0]
  ]

  rows.forEach((row) => {
    const worksheetRow = worksheet.addRow(row.map((value) => sanitizeCell(value)))
    if (row[0] === 'EXPORT SUMMARY' || row[0] === 'RECORD COUNTS') {
      worksheetRow.getCell(1).font = { bold: true, size: 13, color: { argb: 'FF1F4E79' } }
    } else if (row[0] === 'TOTAL RECORDS EXPORTED') {
      worksheetRow.getCell(1).font = { bold: true, size: 11 }
      worksheetRow.getCell(2).font = { bold: true, size: 11, color: { argb: 'FF00B050' } }
    }
    worksheetRow.height = 20
  })

  return worksheet
}

const styleHeaderRow = (worksheet) => {
  worksheet.getRow(1).eachCell((cell) => {
    Object.assign(cell, STYLES.header)
  })
  worksheet.getRow(1).height = 30
}

const styleDataRows = (worksheet, startRow, endRow) => {
  if (!endRow || endRow < startRow) return

  for (let rowNumber = startRow; rowNumber <= endRow; rowNumber += 1) {
    const row = worksheet.getRow(rowNumber)
    const style = rowNumber % 2 === 0 ? STYLES.rowEven : STYLES.rowOdd
    row.eachCell({ includeEmpty: true }, (cell) => {
      cell.fill = style.fill
      cell.alignment = { vertical: 'middle', wrapText: false }
      cell.border = {
        top: { style: 'hair' },
        bottom: { style: 'hair' },
        left: { style: 'hair' },
        right: { style: 'hair' }
      }
    })
    row.height = 18
  }
}

const autoFitColumns = (worksheet) => {
  worksheet.columns.forEach((column) => {
    let maxLength = column.header ? String(column.header).length : 10
    column.eachCell({ includeEmpty: false }, (cell) => {
      const length = cell.value ? String(cell.value).length : 0
      if (length > maxLength) maxLength = length
    })
    column.width = Math.min(Math.max(maxLength + 3, 12), 45)
  })
}

module.exports = {
  STYLES,
  addSummarySheet,
  autoFitColumns,
  createWorkbook,
  styleDataRows,
  styleHeaderRow
}
